using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Game
{
    public static class LevelCode
    {
        public static int GetLevelNumber(string levelCode)
        {
            switch (levelCode)
            {
                case "J44SW":
                    return 0;
                case "DW4C6":
                    return 1;
                case "TNPWW":
                    return 2;
                case "HBA3H":
                    return 3;
                case "E42DC":
                    return 4;
                case "V7NTC":
                    return 5;
                case "2ZLQS":
                    return 6;
                case "ZHD3S":
                    return 7;
                case "L6EGU":
                    return 8;
                case "TAXNE":
                    return 9;
                case "6MLDN":
                    return 10;
                case "PCZPA":
                    return 11;
                case "EHJ8D":
                    return 12;
                case "2B8D6":
                    return 13;
                case "A6GJ6":
                    return 14;
                case "HXUSS":
                    return 15;
                case "VHAPF":
                    return 16;
                case "PPHBD":
                    return 17;
                case "XRW2M":
                    return 18;
                case "CWEC2":
                    return 19;
                case "RBURE":
                    return 20;
                case "8EBGF":
                    return 21;
                case "YQG6N":
                    return 22;
                case "6G33X":
                    return 23;
                case "M268G":
                    return 24;
                case "RJN63":
                    return 25;
                case "TSSYA":
                    return 26;
                case "TWSKG":
                    return 27;
                case "JNB5N":
                    return 28;
                case "GJZNQ":
                    return 29;
                case "53LMP":
                    return 30;
                case "YDUJV":
                    return 31;
                case "YYDMU":
                    return 32;
                case "F7R63":
                    return 33;
                case "HXSUN":
                    return 34;
                case "7YBUA":
                    return 35;
                case "GRAQ7":
                    return 36;
                case "YGEKJ":
                    return 37;
                case "QCJWR":
                    return 38;
                case "TJXJH":
                    return 39;
                case "J24TH":
                    return 40;
                case "FKZ8Q":
                    return 41;
                case "8CAHN":
                    return 42;
                case "GYWP4":
                    return 43;
                case "82FVM":
                    return 44;
                case "EN4D4":
                    return 45;
                case "WBZMY":
                    return 46;
                case "PWPGZ":
                    return 47;
                case "PPF4K":
                    return 48;
                case "MCAJJ":
                    return 49;
                case "3VHNH":
                    return 50;
                case "QUGFC":
                    return 51;
                case "2PVD2":
                    return 52;
                case "6KWS8":
                    return 53;
                case "SJPWN":
                    return 54;
                case "SULK8":
                    return 55;
                case "CNU3A":
                    return 56;
                case "B3MDH":
                    return 57;
                case "4PHE8":
                    return 58;
                case "A3CCN":
                    return 59;
                case "CPRKY":
                    return 60;
                case "TFT8Y":
                    return 61;
                case "5J6FA":
                    return 62;
                case "N32CY":
                    return 63;
                case "D7SJD":
                    return 64;
                case "DAKXN":
                    return 65;
                case "YSJ66":
                    return 66;
                case "W5KDQ":
                    return 67;
                case "5HMNM":
                    return 68;
                case "TSBDU":
                    return 69;
                case "GA8LK":
                    return 70;
                case "D5HFV":
                    return 71;
                case "S44UA":
                    return 72;
                case "L88JM":
                    return 73;
                case "RRXV4":
                    return 74;
                case "4UE5T":
                    return 75;
                case "T8FDF":
                    return 76;
                case "XT7V2":
                    return 77;
                case "ZWEQ6":
                    return 78;
                case "AMZMB":
                    return 79;
                case "US2ZC":
                    return 80;
                case "XLLQP":
                    return 81;
                case "SYLUC":
                    return 82;
                case "TWYNL":
                    return 83;
                case "2BMQU":
                    return 84;
                case "3LGX4":
                    return 85;
                case "Q3Z47":
                    return 86;
                case "AFPBQ":
                    return 87;
                case "LGQFJ":
                    return 88;
                case "ALSNM":
                    return 89;
                case "LVLBH":
                    return 90;
                case "SFLEJ":
                    return 91;
                case "MDWV7":
                    return 92;
                case "X8RVB":
                    return 93;
                case "MHX68":
                    return 94;
                case "TUFFU":
                    return 95;
                case "R23LS":
                    return 96;
                case "3RXUP":
                    return 97;
                case "44KZD":
                    return 98;
                case "GT4GT":
                    return 99;
                case "B35L8":
                    return 100;
                case "D6NCW":
                    return 101;
                case "78ET2":
                    return 102;
                case "TJKCE":
                    return 103;
                case "GJ5GG":
                    return 104;
                case "S773Z":
                    return 105;
                case "AY7US":
                    return 106;
                case "W5RLP":
                    return 107;
                case "5CV6R":
                    return 108;
                case "4XY8S":
                    return 109;
                case "7HZCM":
                    return 110;
                case "Z6XDP":
                    return 111;
                case "E8UKW":
                    return 112;
                case "GASAE":
                    return 113;
                case "X27WH":
                    return 114;
                case "EV8YM":
                    return 115;
                case "3G8J3":
                    return 116;
                case "285HZ":
                    return 117;
                case "YGN6J":
                    return 118;
                case "6RLJJ":
                    return 119;
                case "3FY34":
                    return 120;
                case "EJC4H":
                    return 121;
                case "E78YU":
                    return 122;
                case "7AKQ5":
                    return 123;
                case "HEKHP":
                    return 124;
                case "QNBNK":
                    return 125;
                case "VKYPT":
                    return 126;
                case "WQEPW":
                    return 127;
                case "R5AAV":
                    return 128;
                case "ZGWKK":
                    return 129;
                case "6F5MA":
                    return 130;
                case "W5RNM":
                    return 131;
                case "ZHXTU":
                    return 132;
                case "4HSF7":
                    return 133;
                case "R452N":
                    return 134;
                case "MDJUW":
                    return 135;
                case "JYZDN":
                    return 136;
                case "QNLP5":
                    return 137;
                case "28ZB5":
                    return 138;
                case "JFQP2":
                    return 139;
                case "SXQM3":
                    return 140;
                case "CKC8W":
                    return 141;
                case "TU5ZD":
                    return 142;
                case "BRUEE":
                    return 143;
                case "P5DKE":
                    return 144;
                case "RD45E":
                    return 145;
                case "FW43D":
                    return 146;
                case "TJNKL":
                    return 147;
                case "ELLZK":
                    return 148;
                case "FD864":
                    return 149;
                case "ZUKJL":
                    return 150;
                case "VUEGK":
                    return 151;
                case "7QF4Q":
                    return 152;
                case "5YBVT":
                    return 153;
                case "ZDK38":
                    return 154;
                case "DSL87":
                    return 155;
                case "ND6AM":
                    return 156;
                case "ULTQQ":
                    return 157;
                case "8EF8M":
                    return 158;
                case "XEQKP":
                    return 159;
                case "QBMMD":
                    return 160;
                case "WJQKH":
                    return 161;
                case "DHEH5":
                    return 162;
                case "4SFR4":
                    return 163;
                case "SFTET":
                    return 164;
                case "V6KQJ":
                    return 165;
                case "7CATR":
                    return 166;
                case "MZS6X":
                    return 167;
                case "K4JHM":
                    return 168;
                case "Y87DS":
                    return 169;
                case "E88Q5":
                    return 170;
                case "JQG2Q":
                    return 171;
                case "Z8AAK":
                    return 172;
                case "AGTYR":
                    return 173;
                case "CAH3S":
                    return 174;
                case "X5L24":
                    return 175;
                case "V8F7E":
                    return 176;
                case "8DTXG":
                    return 177;
                case "6SZP6":
                    return 178;
                case "L4H6L":
                    return 179;
                case "RNGUP":
                    return 180;
                case "EYE6G":
                    return 181;
                case "NDP74":
                    return 182;
                case "22C5L":
                    return 183;
                case "6V5SU":
                    return 184;
                case "TJ25G":
                    return 185;
                case "3WNPL":
                    return 186;
                case "G2US8":
                    return 187;
                case "H7WR3":
                    return 188;
                case "2D2UE":
                    return 189;
                case "SZMUN":
                    return 190;
                case "5SWA5":
                    return 191;
                case "56HXM":
                    return 192;
                case "YXAVV":
                    return 193;
                case "8GT5C":
                    return 194;
                case "88NX2":
                    return 195;
                case "PQGYW":
                    return 196;
                case "BJ3AQ":
                    return 197;
                case "XDTWD":
                    return 198;
                case "KX7DC":
                    return 199;
                case "DDE7E":
                    return 200;
                case "LGRSP":
                    return 201;
                case "5E8GP":
                    return 202;
                case "NYRBK":
                    return 203;
                case "Q5AF7":
                    return 204;
                case "5V6Z2":
                    return 205;
                case "KAJUX":
                    return 206;
                case "LKHUL":
                    return 207;
                case "42JTT":
                    return 208;
                case "SDLGX":
                    return 209;
                case "UF63V":
                    return 210;
                case "GD8AJ":
                    return 211;
                case "XKYZE":
                    return 212;
                case "54MSC":
                    return 213;
                case "DQ6XQ":
                    return 214;
                case "WUPVN":
                    return 215;
                case "ZKXCF":
                    return 216;
                case "DCQ8Q":
                    return 217;
                case "HLHKW":
                    return 218;
                case "SCSPW":
                    return 219;
                case "XY3DU":
                    return 220;
                case "DHGL7":
                    return 221;
                case "VWMUR":
                    return 222;
                case "NUWTA":
                    return 223;
                case "2MNB4":
                    return 224;
                case "ZGVB6":
                    return 225;
                case "UBA7Y":
                    return 226;
                case "BQTQB":
                    return 227;
                case "55DA4":
                    return 228;
                case "T7V3J":
                    return 229;
                case "7P8N5":
                    return 230;
                case "KLZJ3":
                    return 231;
                case "5VFPM":
                    return 232;
                case "TWN5Q":
                    return 233;
                case "6AFRE":
                    return 234;
                case "6JNGJ":
                    return 235;
                case "3U228":
                    return 236;
                case "FCUCN":
                    return 237;
                case "YYKVE":
                    return 238;
                case "HYXWJ":
                    return 239;
                case "6SZLL":
                    return 240;
                case "6HQH7":
                    return 241;
                case "B6T8A":
                    return 242;
                case "K3MQF":
                    return 243;
                case "RBLQZ":
                    return 244;
                case "GXTL5":
                    return 245;
                case "GTZ6M":
                    return 246;
                case "J3QPB":
                    return 247;
                case "7ULDM":
                    return 248;
                case "2FLV4":
                    return 249;
                case "PLGQ2":
                    return 250;
                case "4GJUE":
                    return 251;
                case "GXELZ":
                    return 252;
                case "QFVUY":
                    return 253;
                case "RM6NH":
                    return 254;
                case "5XGD8":
                    return 255;
                case "BM6RQ":
                    return 256;
                case "4LKER":
                    return 257;
                case "CS4K4":
                    return 258;
                case "JQAM5":
                    return 259;
                case "USY5L":
                    return 260;
                case "CN3G5":
                    return 261;
                case "F8FVD":
                    return 262;
                case "4ZV55":
                    return 263;
                case "D5QDW":
                    return 264;
                case "7RVS8":
                    return 265;
                case "PX4HM":
                    return 266;
                case "RVBEN":
                    return 267;
                case "QSCJL":
                    return 268;
                case "CMHFA":
                    return 269;
                case "R4DQZ":
                    return 270;
                case "YCVGN":
                    return 271;
                case "UZJGQ":
                    return 272;
                case "QD6HU":
                    return 273;
                case "HXQQP":
                    return 274;
                case "U2GZT":
                    return 275;
                case "THPSQ":
                    return 276;
                case "UTNRV":
                    return 277;
                case "N83Z3":
                    return 278;
                case "XH534":
                    return 279;
                case "7QAUZ":
                    return 280;
                case "3MVAE":
                    return 281;
                case "654V3":
                    return 282;
                case "LKYY4":
                    return 283;
                case "5YPUF":
                    return 284;
                case "H4YWZ":
                    return 285;
                case "M6N6U":
                    return 286;
                case "DH4ZW":
                    return 287;
                case "G6NLY":
                    return 288;
                case "SDF6Q":
                    return 289;
                case "MRE77":
                    return 290;
                case "HANNR":
                    return 291;
                case "7W8H2":
                    return 292;
                case "8R7BY":
                    return 293;
                case "DQ7CV":
                    return 294;
                case "8KD5W":
                    return 295;
                case "EW2GN":
                    return 296;
                case "42P7M":
                    return 297;
                case "C3QJX":
                    return 298;
                case "T7FSY":
                    return 299;
                case "BEEGL":
                    return 300;
                case "6SBK8":
                    return 301;
                case "66RYM":
                    return 302;
                case "K5247":
                    return 303;
                case "GBAWV":
                    return 304;
                case "J8XNC":
                    return 305;
                case "AETEU":
                    return 306;
                case "8RT4R":
                    return 307;
                case "KYE8P":
                    return 308;
                case "FLZ5N":
                    return 309;
                case "XFLUS":
                    return 310;
                case "AEQUC":
                    return 311;
                case "63WG7":
                    return 312;
                case "2MMEM":
                    return 313;
                case "2K7LV":
                    return 314;
                case "Q5BHQ":
                    return 315;
                case "7H3AM":
                    return 316;
                case "437VU":
                    return 317;
                case "3B7ZT":
                    return 318;
                case "QB6AW":
                    return 319;
                case "28URU":
                    return 320;
                case "MG87C":
                    return 321;
                case "EDHED":
                    return 322;
                case "XAW3D":
                    return 323;
                case "7NYSS":
                    return 324;
                case "ZMFZF":
                    return 325;
                case "N7AUW":
                    return 326;
                case "8VKNA":
                    return 327;
                case "V4ATQ":
                    return 328;
                case "Y33V5":
                    return 329;
                case "PMC5X":
                    return 330;
                case "NHC74":
                    return 331;
                case "ABG2W":
                    return 332;
                case "FCVQE":
                    return 333;
                case "CYJ3Q":
                    return 334;
                case "CNFC3":
                    return 335;
                case "7SS5Y":
                    return 336;
                case "A4D6J":
                    return 337;
                case "ZTLTA":
                    return 338;
                case "UWH5J":
                    return 339;
                case "VFMR3":
                    return 340;
                case "YDJPU":
                    return 341;
                case "AB8E5":
                    return 342;
                case "QRKBV":
                    return 343;
                case "K7YFN":
                    return 344;
                case "RMY25":
                    return 345;
                case "PEK3F":
                    return 346;
                case "ZFBC8":
                    return 347;
                case "6UXKJ":
                    return 348;
                case "YUGWT":
                    return 349;
                case "CLFJ8":
                    return 350;
                case "WQFDK":
                    return 351;
                case "MNQSE":
                    return 352;
                case "4YF7E":
                    return 353;
                case "JQHBY":
                    return 354;
                case "YJN6W":
                    return 355;
                case "6EBH3":
                    return 356;
                case "D7B4S":
                    return 357;
                case "KA72V":
                    return 358;
                case "RDFEP":
                    return 359;
                case "8NJRJ":
                    return 360;
                case "UDESH":
                    return 361;
                case "NBJPM":
                    return 362;
                case "HLHYB":
                    return 363;
                case "5XLN4":
                    return 364;
                case "HSPPG":
                    return 365;
                case "VDJQX":
                    return 366;
                case "R4T8G":
                    return 367;
                case "A3RUD":
                    return 368;
                case "HZRNM":
                    return 369;
                case "F5PDS":
                    return 370;
                case "JC4WA":
                    return 371;
                case "CWXLV":
                    return 372;
                case "K22Y4":
                    return 373;
                case "M2HRB":
                    return 374;
                case "BGYJU":
                    return 375;
                case "RABBB":
                    return 376;
                case "ZWE7N":
                    return 377;
                case "PA57D":
                    return 378;
                case "LDF83":
                    return 379;
                case "Q82TA":
                    return 380;
                case "NV7CQ":
                    return 381;
                case "CMTBS":
                    return 382;
                case "CVVK4":
                    return 383;
                case "WV4LP":
                    return 384;
                case "L5KNX":
                    return 385;
                case "7AZQE":
                    return 386;
                case "SHRBV":
                    return 387;
                case "DYCQL":
                    return 388;
                case "CP3PB":
                    return 389;
                case "YR5DF":
                    return 390;
                case "3EQDW":
                    return 391;
                case "RKSMS":
                    return 392;
                case "BUD68":
                    return 393;
                case "4EUWZ":
                    return 394;
                case "6TM8M":
                    return 395;
                case "6C5M8":
                    return 396;
                case "PEVJK":
                    return 397;
                case "NZMME":
                    return 398;
                case "3FX6J":
                    return 399;
                case "QL5PF":
                    return 400;
                case "U5GMH":
                    return 401;
                case "JZQZZ":
                    return 402;
                case "NPFNC":
                    return 403;
                case "583VU":
                    return 404;
                case "CZHR7":
                    return 405;
                case "Z4QY6":
                    return 406;
                case "TFPFN":
                    return 407;
                case "T7JAA":
                    return 408;
                case "WKVUZ":
                    return 409;
                case "M8J3M":
                    return 410;
                case "QSJ3C":
                    return 411;
                case "3WYPR":
                    return 412;
                case "PKZ4G":
                    return 413;
                case "HA8AS":
                    return 414;
                case "7X2U7":
                    return 415;
                case "2EVZT":
                    return 416;
                case "ZUVLP":
                    return 417;
                case "B5UCT":
                    return 418;
                case "6H4SU":
                    return 419;
                case "MT2NR":
                    return 420;
                case "MAHKP":
                    return 421;
                case "ZYX5K":
                    return 422;
                case "XA74Z":
                    return 423;
                case "4WNNE":
                    return 424;
                case "LN5QU":
                    return 425;
                case "Y4H8U":
                    return 426;
                case "GLGHG":
                    return 427;
                case "ZLK5W":
                    return 428;
                case "KGY25":
                    return 429;
                case "5J82Z":
                    return 430;
                case "XEMJF":
                    return 431;
                case "7D2XY":
                    return 432;
                case "5QXJC":
                    return 433;
                case "L2XV8":
                    return 434;
                case "RLSZ4":
                    return 435;
                case "EXDUX":
                    return 436;
                case "P5QH6":
                    return 437;
                case "C87CJ":
                    return 438;
                case "WSVFZ":
                    return 439;
                case "3RPYS":
                    return 440;
                case "DUL2H":
                    return 441;
                case "LVVNB":
                    return 442;
                case "J8G8K":
                    return 443;
                case "AAQMA":
                    return 444;
                case "L4VML":
                    return 445;
                case "7YL8A":
                    return 446;
                case "VHNBU":
                    return 447;
                case "4SX8T":
                    return 448;
                case "PLSA8":
                    return 449;
                case "WLV4Z":
                    return 450;
                case "3BBYG":
                    return 451;
                case "J78PJ":
                    return 452;
                case "VJVNN":
                    return 453;
                case "AUFNQ":
                    return 454;
                case "RKQ3T":
                    return 455;
                case "AKUMX":
                    return 456;
                case "VDRHF":
                    return 457;
                case "UGX4L":
                    return 458;
                case "5THY7":
                    return 459;
                case "FYDV8":
                    return 460;
                case "BFGNJ":
                    return 461;
                case "RTHEF":
                    return 462;
                case "7MUYW":
                    return 463;
                case "S2NH2":
                    return 464;
                case "36LBT":
                    return 465;
                case "7CZ5M":
                    return 466;
                case "JF7NW":
                    return 467;
                case "Q5C8W":
                    return 468;
                case "A8SWM":
                    return 469;
                case "S7SCP":
                    return 470;
                case "NK53F":
                    return 471;
                case "D4F3L":
                    return 472;
                case "P3L25":
                    return 473;
                case "2NGBG":
                    return 474;
                case "VXPTZ":
                    return 475;
                case "3NXXB":
                    return 476;
                case "8SXQ8":
                    return 477;
                case "8JEHT":
                    return 478;
                case "VYJWG":
                    return 479;
                case "GVYZU":
                    return 480;
                case "EZQ52":
                    return 481;
                case "X5KCL":
                    return 482;
                case "XEQ2L":
                    return 483;
                case "6E536":
                    return 484;
                case "RJ7RT":
                    return 485;
                case "6PZMT":
                    return 486;
                case "GW6C5":
                    return 487;
                case "HC3WJ":
                    return 488;
                case "C7B64":
                    return 489;
                case "QHQLK":
                    return 490;
                case "BZ63C":
                    return 491;
                case "527K4":
                    return 492;
                case "JD7RD":
                    return 493;
                case "BHN5C":
                    return 494;
                case "3LGS3":
                    return 495;
                case "SGBWD":
                    return 496;
                case "X7PBR":
                    return 497;
                case "QZDAA":
                    return 498;
                case "PER38":
                    return 499;
                default:
                    return -1;
            }
        }
        public static string GetLevelCode(int levelNumber)
        {
            switch (levelNumber)
            {
                case 0:
                    return "J44SW";
                case 1:
                    return "DW4C6";
                case 2:
                    return "TNPWW";
                case 3:
                    return "HBA3H";
                case 4:
                    return "E42DC";
                case 5:
                    return "V7NTC";
                case 6:
                    return "2ZLQS";
                case 7:
                    return "ZHD3S";
                case 8:
                    return "L6EGU";
                case 9:
                    return "TAXNE";
                case 10:
                    return "6MLDN";
                case 11:
                    return "PCZPA";
                case 12:
                    return "EHJ8D";
                case 13:
                    return "2B8D6";
                case 14:
                    return "A6GJ6";
                case 15:
                    return "HXUSS";
                case 16:
                    return "VHAPF";
                case 17:
                    return "PPHBD";
                case 18:
                    return "XRW2M";
                case 19:
                    return "CWEC2";
                case 20:
                    return "RBURE";
                case 21:
                    return "8EBGF";
                case 22:
                    return "YQG6N";
                case 23:
                    return "6G33X";
                case 24:
                    return "M268G";
                case 25:
                    return "RJN63";
                case 26:
                    return "TSSYA";
                case 27:
                    return "TWSKG";
                case 28:
                    return "JNB5N";
                case 29:
                    return "GJZNQ";
                case 30:
                    return "53LMP";
                case 31:
                    return "YDUJV";
                case 32:
                    return "YYDMU";
                case 33:
                    return "F7R63";
                case 34:
                    return "HXSUN";
                case 35:
                    return "7YBUA";
                case 36:
                    return "GRAQ7";
                case 37:
                    return "YGEKJ";
                case 38:
                    return "QCJWR";
                case 39:
                    return "TJXJH";
                case 40:
                    return "J24TH";
                case 41:
                    return "FKZ8Q";
                case 42:
                    return "8CAHN";
                case 43:
                    return "GYWP4";
                case 44:
                    return "82FVM";
                case 45:
                    return "EN4D4";
                case 46:
                    return "WBZMY";
                case 47:
                    return "PWPGZ";
                case 48:
                    return "PPF4K";
                case 49:
                    return "MCAJJ";
                case 50:
                    return "3VHNH";
                case 51:
                    return "QUGFC";
                case 52:
                    return "2PVD2";
                case 53:
                    return "6KWS8";
                case 54:
                    return "SJPWN";
                case 55:
                    return "SULK8";
                case 56:
                    return "CNU3A";
                case 57:
                    return "B3MDH";
                case 58:
                    return "4PHE8";
                case 59:
                    return "A3CCN";
                case 60:
                    return "CPRKY";
                case 61:
                    return "TFT8Y";
                case 62:
                    return "5J6FA";
                case 63:
                    return "N32CY";
                case 64:
                    return "D7SJD";
                case 65:
                    return "DAKXN";
                case 66:
                    return "YSJ66";
                case 67:
                    return "W5KDQ";
                case 68:
                    return "5HMNM";
                case 69:
                    return "TSBDU";
                case 70:
                    return "GA8LK";
                case 71:
                    return "D5HFV";
                case 72:
                    return "S44UA";
                case 73:
                    return "L88JM";
                case 74:
                    return "RRXV4";
                case 75:
                    return "4UE5T";
                case 76:
                    return "T8FDF";
                case 77:
                    return "XT7V2";
                case 78:
                    return "ZWEQ6";
                case 79:
                    return "AMZMB";
                case 80:
                    return "US2ZC";
                case 81:
                    return "XLLQP";
                case 82:
                    return "SYLUC";
                case 83:
                    return "TWYNL";
                case 84:
                    return "2BMQU";
                case 85:
                    return "3LGX4";
                case 86:
                    return "Q3Z47";
                case 87:
                    return "AFPBQ";
                case 88:
                    return "LGQFJ";
                case 89:
                    return "ALSNM";
                case 90:
                    return "LVLBH";
                case 91:
                    return "SFLEJ";
                case 92:
                    return "MDWV7";
                case 93:
                    return "X8RVB";
                case 94:
                    return "MHX68";
                case 95:
                    return "TUFFU";
                case 96:
                    return "R23LS";
                case 97:
                    return "3RXUP";
                case 98:
                    return "44KZD";
                case 99:
                    return "GT4GT";
                case 100:
                    return "B35L8";
                case 101:
                    return "D6NCW";
                case 102:
                    return "78ET2";
                case 103:
                    return "TJKCE";
                case 104:
                    return "GJ5GG";
                case 105:
                    return "S773Z";
                case 106:
                    return "AY7US";
                case 107:
                    return "W5RLP";
                case 108:
                    return "5CV6R";
                case 109:
                    return "4XY8S";
                case 110:
                    return "7HZCM";
                case 111:
                    return "Z6XDP";
                case 112:
                    return "E8UKW";
                case 113:
                    return "GASAE";
                case 114:
                    return "X27WH";
                case 115:
                    return "EV8YM";
                case 116:
                    return "3G8J3";
                case 117:
                    return "285HZ";
                case 118:
                    return "YGN6J";
                case 119:
                    return "6RLJJ";
                case 120:
                    return "3FY34";
                case 121:
                    return "EJC4H";
                case 122:
                    return "E78YU";
                case 123:
                    return "7AKQ5";
                case 124:
                    return "HEKHP";
                case 125:
                    return "QNBNK";
                case 126:
                    return "VKYPT";
                case 127:
                    return "WQEPW";
                case 128:
                    return "R5AAV";
                case 129:
                    return "ZGWKK";
                case 130:
                    return "6F5MA";
                case 131:
                    return "W5RNM";
                case 132:
                    return "ZHXTU";
                case 133:
                    return "4HSF7";
                case 134:
                    return "R452N";
                case 135:
                    return "MDJUW";
                case 136:
                    return "JYZDN";
                case 137:
                    return "QNLP5";
                case 138:
                    return "28ZB5";
                case 139:
                    return "JFQP2";
                case 140:
                    return "SXQM3";
                case 141:
                    return "CKC8W";
                case 142:
                    return "TU5ZD";
                case 143:
                    return "BRUEE";
                case 144:
                    return "P5DKE";
                case 145:
                    return "RD45E";
                case 146:
                    return "FW43D";
                case 147:
                    return "TJNKL";
                case 148:
                    return "ELLZK";
                case 149:
                    return "FD864";
                case 150:
                    return "ZUKJL";
                case 151:
                    return "VUEGK";
                case 152:
                    return "7QF4Q";
                case 153:
                    return "5YBVT";
                case 154:
                    return "ZDK38";
                case 155:
                    return "DSL87";
                case 156:
                    return "ND6AM";
                case 157:
                    return "ULTQQ";
                case 158:
                    return "8EF8M";
                case 159:
                    return "XEQKP";
                case 160:
                    return "QBMMD";
                case 161:
                    return "WJQKH";
                case 162:
                    return "DHEH5";
                case 163:
                    return "4SFR4";
                case 164:
                    return "SFTET";
                case 165:
                    return "V6KQJ";
                case 166:
                    return "7CATR";
                case 167:
                    return "MZS6X";
                case 168:
                    return "K4JHM";
                case 169:
                    return "Y87DS";
                case 170:
                    return "E88Q5";
                case 171:
                    return "JQG2Q";
                case 172:
                    return "Z8AAK";
                case 173:
                    return "AGTYR";
                case 174:
                    return "CAH3S";
                case 175:
                    return "X5L24";
                case 176:
                    return "V8F7E";
                case 177:
                    return "8DTXG";
                case 178:
                    return "6SZP6";
                case 179:
                    return "L4H6L";
                case 180:
                    return "RNGUP";
                case 181:
                    return "EYE6G";
                case 182:
                    return "NDP74";
                case 183:
                    return "22C5L";
                case 184:
                    return "6V5SU";
                case 185:
                    return "TJ25G";
                case 186:
                    return "3WNPL";
                case 187:
                    return "G2US8";
                case 188:
                    return "H7WR3";
                case 189:
                    return "2D2UE";
                case 190:
                    return "SZMUN";
                case 191:
                    return "5SWA5";
                case 192:
                    return "56HXM";
                case 193:
                    return "YXAVV";
                case 194:
                    return "8GT5C";
                case 195:
                    return "88NX2";
                case 196:
                    return "PQGYW";
                case 197:
                    return "BJ3AQ";
                case 198:
                    return "XDTWD";
                case 199:
                    return "KX7DC";
                case 200:
                    return "DDE7E";
                case 201:
                    return "LGRSP";
                case 202:
                    return "5E8GP";
                case 203:
                    return "NYRBK";
                case 204:
                    return "Q5AF7";
                case 205:
                    return "5V6Z2";
                case 206:
                    return "KAJUX";
                case 207:
                    return "LKHUL";
                case 208:
                    return "42JTT";
                case 209:
                    return "SDLGX";
                case 210:
                    return "UF63V";
                case 211:
                    return "GD8AJ";
                case 212:
                    return "XKYZE";
                case 213:
                    return "54MSC";
                case 214:
                    return "DQ6XQ";
                case 215:
                    return "WUPVN";
                case 216:
                    return "ZKXCF";
                case 217:
                    return "DCQ8Q";
                case 218:
                    return "HLHKW";
                case 219:
                    return "SCSPW";
                case 220:
                    return "XY3DU";
                case 221:
                    return "DHGL7";
                case 222:
                    return "VWMUR";
                case 223:
                    return "NUWTA";
                case 224:
                    return "2MNB4";
                case 225:
                    return "ZGVB6";
                case 226:
                    return "UBA7Y";
                case 227:
                    return "BQTQB";
                case 228:
                    return "55DA4";
                case 229:
                    return "T7V3J";
                case 230:
                    return "7P8N5";
                case 231:
                    return "KLZJ3";
                case 232:
                    return "5VFPM";
                case 233:
                    return "TWN5Q";
                case 234:
                    return "6AFRE";
                case 235:
                    return "6JNGJ";
                case 236:
                    return "3U228";
                case 237:
                    return "FCUCN";
                case 238:
                    return "YYKVE";
                case 239:
                    return "HYXWJ";
                case 240:
                    return "6SZLL";
                case 241:
                    return "6HQH7";
                case 242:
                    return "B6T8A";
                case 243:
                    return "K3MQF";
                case 244:
                    return "RBLQZ";
                case 245:
                    return "GXTL5";
                case 246:
                    return "GTZ6M";
                case 247:
                    return "J3QPB";
                case 248:
                    return "7ULDM";
                case 249:
                    return "2FLV4";
                case 250:
                    return "PLGQ2";
                case 251:
                    return "4GJUE";
                case 252:
                    return "GXELZ";
                case 253:
                    return "QFVUY";
                case 254:
                    return "RM6NH";
                case 255:
                    return "5XGD8";
                case 256:
                    return "BM6RQ";
                case 257:
                    return "4LKER";
                case 258:
                    return "CS4K4";
                case 259:
                    return "JQAM5";
                case 260:
                    return "USY5L";
                case 261:
                    return "CN3G5";
                case 262:
                    return "F8FVD";
                case 263:
                    return "4ZV55";
                case 264:
                    return "D5QDW";
                case 265:
                    return "7RVS8";
                case 266:
                    return "PX4HM";
                case 267:
                    return "RVBEN";
                case 268:
                    return "QSCJL";
                case 269:
                    return "CMHFA";
                case 270:
                    return "R4DQZ";
                case 271:
                    return "YCVGN";
                case 272:
                    return "UZJGQ";
                case 273:
                    return "QD6HU";
                case 274:
                    return "HXQQP";
                case 275:
                    return "U2GZT";
                case 276:
                    return "THPSQ";
                case 277:
                    return "UTNRV";
                case 278:
                    return "N83Z3";
                case 279:
                    return "XH534";
                case 280:
                    return "7QAUZ";
                case 281:
                    return "3MVAE";
                case 282:
                    return "654V3";
                case 283:
                    return "LKYY4";
                case 284:
                    return "5YPUF";
                case 285:
                    return "H4YWZ";
                case 286:
                    return "M6N6U";
                case 287:
                    return "DH4ZW";
                case 288:
                    return "G6NLY";
                case 289:
                    return "SDF6Q";
                case 290:
                    return "MRE77";
                case 291:
                    return "HANNR";
                case 292:
                    return "7W8H2";
                case 293:
                    return "8R7BY";
                case 294:
                    return "DQ7CV";
                case 295:
                    return "8KD5W";
                case 296:
                    return "EW2GN";
                case 297:
                    return "42P7M";
                case 298:
                    return "C3QJX";
                case 299:
                    return "T7FSY";
                case 300:
                    return "BEEGL";
                case 301:
                    return "6SBK8";
                case 302:
                    return "66RYM";
                case 303:
                    return "K5247";
                case 304:
                    return "GBAWV";
                case 305:
                    return "J8XNC";
                case 306:
                    return "AETEU";
                case 307:
                    return "8RT4R";
                case 308:
                    return "KYE8P";
                case 309:
                    return "FLZ5N";
                case 310:
                    return "XFLUS";
                case 311:
                    return "AEQUC";
                case 312:
                    return "63WG7";
                case 313:
                    return "2MMEM";
                case 314:
                    return "2K7LV";
                case 315:
                    return "Q5BHQ";
                case 316:
                    return "7H3AM";
                case 317:
                    return "437VU";
                case 318:
                    return "3B7ZT";
                case 319:
                    return "QB6AW";
                case 320:
                    return "28URU";
                case 321:
                    return "MG87C";
                case 322:
                    return "EDHED";
                case 323:
                    return "XAW3D";
                case 324:
                    return "7NYSS";
                case 325:
                    return "ZMFZF";
                case 326:
                    return "N7AUW";
                case 327:
                    return "8VKNA";
                case 328:
                    return "V4ATQ";
                case 329:
                    return "Y33V5";
                case 330:
                    return "PMC5X";
                case 331:
                    return "NHC74";
                case 332:
                    return "ABG2W";
                case 333:
                    return "FCVQE";
                case 334:
                    return "CYJ3Q";
                case 335:
                    return "CNFC3";
                case 336:
                    return "7SS5Y";
                case 337:
                    return "A4D6J";
                case 338:
                    return "ZTLTA";
                case 339:
                    return "UWH5J";
                case 340:
                    return "VFMR3";
                case 341:
                    return "YDJPU";
                case 342:
                    return "AB8E5";
                case 343:
                    return "QRKBV";
                case 344:
                    return "K7YFN";
                case 345:
                    return "RMY25";
                case 346:
                    return "PEK3F";
                case 347:
                    return "ZFBC8";
                case 348:
                    return "6UXKJ";
                case 349:
                    return "YUGWT";
                case 350:
                    return "CLFJ8";
                case 351:
                    return "WQFDK";
                case 352:
                    return "MNQSE";
                case 353:
                    return "4YF7E";
                case 354:
                    return "JQHBY";
                case 355:
                    return "YJN6W";
                case 356:
                    return "6EBH3";
                case 357:
                    return "D7B4S";
                case 358:
                    return "KA72V";
                case 359:
                    return "RDFEP";
                case 360:
                    return "8NJRJ";
                case 361:
                    return "UDESH";
                case 362:
                    return "NBJPM";
                case 363:
                    return "HLHYB";
                case 364:
                    return "5XLN4";
                case 365:
                    return "HSPPG";
                case 366:
                    return "VDJQX";
                case 367:
                    return "R4T8G";
                case 368:
                    return "A3RUD";
                case 369:
                    return "HZRNM";
                case 370:
                    return "F5PDS";
                case 371:
                    return "JC4WA";
                case 372:
                    return "CWXLV";
                case 373:
                    return "K22Y4";
                case 374:
                    return "M2HRB";
                case 375:
                    return "BGYJU";
                case 376:
                    return "RABBB";
                case 377:
                    return "ZWE7N";
                case 378:
                    return "PA57D";
                case 379:
                    return "LDF83";
                case 380:
                    return "Q82TA";
                case 381:
                    return "NV7CQ";
                case 382:
                    return "CMTBS";
                case 383:
                    return "CVVK4";
                case 384:
                    return "WV4LP";
                case 385:
                    return "L5KNX";
                case 386:
                    return "7AZQE";
                case 387:
                    return "SHRBV";
                case 388:
                    return "DYCQL";
                case 389:
                    return "CP3PB";
                case 390:
                    return "YR5DF";
                case 391:
                    return "3EQDW";
                case 392:
                    return "RKSMS";
                case 393:
                    return "BUD68";
                case 394:
                    return "4EUWZ";
                case 395:
                    return "6TM8M";
                case 396:
                    return "6C5M8";
                case 397:
                    return "PEVJK";
                case 398:
                    return "NZMME";
                case 399:
                    return "3FX6J";
                case 400:
                    return "QL5PF";
                case 401:
                    return "U5GMH";
                case 402:
                    return "JZQZZ";
                case 403:
                    return "NPFNC";
                case 404:
                    return "583VU";
                case 405:
                    return "CZHR7";
                case 406:
                    return "Z4QY6";
                case 407:
                    return "TFPFN";
                case 408:
                    return "T7JAA";
                case 409:
                    return "WKVUZ";
                case 410:
                    return "M8J3M";
                case 411:
                    return "QSJ3C";
                case 412:
                    return "3WYPR";
                case 413:
                    return "PKZ4G";
                case 414:
                    return "HA8AS";
                case 415:
                    return "7X2U7";
                case 416:
                    return "2EVZT";
                case 417:
                    return "ZUVLP";
                case 418:
                    return "B5UCT";
                case 419:
                    return "6H4SU";
                case 420:
                    return "MT2NR";
                case 421:
                    return "MAHKP";
                case 422:
                    return "ZYX5K";
                case 423:
                    return "XA74Z";
                case 424:
                    return "4WNNE";
                case 425:
                    return "LN5QU";
                case 426:
                    return "Y4H8U";
                case 427:
                    return "GLGHG";
                case 428:
                    return "ZLK5W";
                case 429:
                    return "KGY25";
                case 430:
                    return "5J82Z";
                case 431:
                    return "XEMJF";
                case 432:
                    return "7D2XY";
                case 433:
                    return "5QXJC";
                case 434:
                    return "L2XV8";
                case 435:
                    return "RLSZ4";
                case 436:
                    return "EXDUX";
                case 437:
                    return "P5QH6";
                case 438:
                    return "C87CJ";
                case 439:
                    return "WSVFZ";
                case 440:
                    return "3RPYS";
                case 441:
                    return "DUL2H";
                case 442:
                    return "LVVNB";
                case 443:
                    return "J8G8K";
                case 444:
                    return "AAQMA";
                case 445:
                    return "L4VML";
                case 446:
                    return "7YL8A";
                case 447:
                    return "VHNBU";
                case 448:
                    return "4SX8T";
                case 449:
                    return "PLSA8";
                case 450:
                    return "WLV4Z";
                case 451:
                    return "3BBYG";
                case 452:
                    return "J78PJ";
                case 453:
                    return "VJVNN";
                case 454:
                    return "AUFNQ";
                case 455:
                    return "RKQ3T";
                case 456:
                    return "AKUMX";
                case 457:
                    return "VDRHF";
                case 458:
                    return "UGX4L";
                case 459:
                    return "5THY7";
                case 460:
                    return "FYDV8";
                case 461:
                    return "BFGNJ";
                case 462:
                    return "RTHEF";
                case 463:
                    return "7MUYW";
                case 464:
                    return "S2NH2";
                case 465:
                    return "36LBT";
                case 466:
                    return "7CZ5M";
                case 467:
                    return "JF7NW";
                case 468:
                    return "Q5C8W";
                case 469:
                    return "A8SWM";
                case 470:
                    return "S7SCP";
                case 471:
                    return "NK53F";
                case 472:
                    return "D4F3L";
                case 473:
                    return "P3L25";
                case 474:
                    return "2NGBG";
                case 475:
                    return "VXPTZ";
                case 476:
                    return "3NXXB";
                case 477:
                    return "8SXQ8";
                case 478:
                    return "8JEHT";
                case 479:
                    return "VYJWG";
                case 480:
                    return "GVYZU";
                case 481:
                    return "EZQ52";
                case 482:
                    return "X5KCL";
                case 483:
                    return "XEQ2L";
                case 484:
                    return "6E536";
                case 485:
                    return "RJ7RT";
                case 486:
                    return "6PZMT";
                case 487:
                    return "GW6C5";
                case 488:
                    return "HC3WJ";
                case 489:
                    return "C7B64";
                case 490:
                    return "QHQLK";
                case 491:
                    return "BZ63C";
                case 492:
                    return "527K4";
                case 493:
                    return "JD7RD";
                case 494:
                    return "BHN5C";
                case 495:
                    return "3LGS3";
                case 496:
                    return "SGBWD";
                case 497:
                    return "X7PBR";
                case 498:
                    return "QZDAA";
                case 499:
                    return "PER38";
                default:
                    throw new SokobanException("No code defined for level: " + levelNumber);
            }
        }
        static readonly string[] codeCharacters = new string[]
            {
                "A", "B", "C", "D", "E", "F", "G",
                "H", "J", "K", "L", "M", "N", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y",
                "Z", "2", "3", "4", "5", "6", "7", "8", "9"
            };
        public static void GenerateLevelCodes()
        {
            Dictionary<string, int> codes = new Dictionary<string, int>();
            Random random = new Random();

            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine(@"public static int GetLevelNumber(string levelCode)
			{
			switch (levelCode)
			{");

            for (int i = 0; i < 500; i++)
            {
                StringBuilder sb = new StringBuilder();
                string code;
                do
                {
                    for (int j = 0; j < 5; j++)
                    {
                        int codeIndex = random.Next(0, codeCharacters.Length - 1);
                        sb.Append(codeCharacters[codeIndex]);
                    }
                    code = sb.ToString();
                } while (codes.ContainsKey(code));
                codes.Add(code, i);
                Console.WriteLine("case \"{0}\":", code);
                Console.WriteLine("\treturn {0};", i);
            }

            Console.WriteLine(@"default:
					return -1;
			}
			}");
            Console.WriteLine();
            Console.WriteLine(@"public static string GetLevelCode(int levelNumber)
			{
			switch (levelNumber)
			{");

            foreach (KeyValuePair<string, int> code in codes)
            {
                Console.WriteLine("case {0}:", code.Value);
                Console.WriteLine("\treturn \"{0}\";", code.Key);
            }

            Console.WriteLine(
                @"default:
					throw new SokobanException(""No code defined for level: "" + levelNumber);
				}
			}");
        }
    }
}
